### ISSUE TITLE
httpx.ConnectError: [WinError 10061]

### ISSUE THREAD

**Issue by Roboxkin** [luigi052005/Ollama-Discord-bot#5]
When running discord_bot.py error 
httpx.ConnectError: [WinError 10061] The connection was not established because the destination computer rejected the connection request

Is there any chance of getting help and corrections? Thank you

**Comment by luigi052005** [comment]
Could you please provide me with more information so that I can replicate the error?

**Comment by Roboxkin** [comment]
> Не могли бы вы предоставить мне дополнительную информацию, чтобы я мог воспроизвести ошибку?

Thank you very much for your answer!
An error occurs when running discord_bot.py
Here is the full error code:
```Python
D:\discord\.venv\Scripts\python.exe D:\discord\Ollama-Discord-bot\discord_bot.py 
Traceback (most recent call last):
  File "D:\discord\.venv\lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "D:\discord\.venv\lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\discord\.venv\lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "D:\discord\.venv\lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "D:\discord\.venv\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "D:\discord\.venv\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "D:\discord\.venv\lib\site-packages\httpcore\_sync\connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "D:\discord\.venv\lib\site-packages\httpcore\_backends\sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\discord\.venv\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [WinError 10061] The connection has not been established because the destination computer rejected the connection request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\discord\Ollama-Discord-bot\discord_bot.py", line 17, in <module>
    pull_model(MODEL)
  File "D:\discord\Ollama-Discord-bot\model_loader.py", line 5, in pull_model
    ollama.chat(MODEL)
  File "D:\discord\.venv\lib\site-packages\ollama\_client.py", line 177, in chat
    return self._request_stream(
  File "D:\discord\.venv\lib\site-packages\ollama\_client.py", line 97, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
  File "D:\discord\.venv\lib\site-packages\ollama\_client.py", line 68, in _request
    response = self._client.request(method, url, **kwargs)
  File "D:\discord\.venv\lib\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\discord\.venv\lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
  File "D:\discord\.venv\lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "D:\discord\.venv\lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "D:\discord\.venv\lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "D:\discord\.venv\lib\site-packages\httpx\_transports\default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\Users\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\discord\.venv\lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10061] ПThe connection has not been established because the destination computer rejected the connection request

Process finished with exit code 1
```

**Comment by luigi052005** [comment]
Update your Ollama library to the latest version. You can download the latest version from https://ollama.com/download

**Comment by Roboxkin** [comment]
I downloaded and installed everything, but there is still an error, which proves that it is prohibited for me.
Looks like you can't fully use it from my country

```Python
D:\discord\.venv\Scripts\python.exe D:\discord\Ollama-Discord-bot\discord_bot.py 
Error: model not found pulling model...
Traceback (most recent call last):
  File "D:\discord\Ollama-Discord-bot\discord_bot.py", line 17, in <module>
    pull_model(MODEL)
  File "D:\discord\Ollama-Discord-bot\model_loader.py", line 9, in pull_model
    ollama.pull(MODEL)
  File "D:\discord\.venv\lib\site-packages\ollama\_client.py", line 220, in pull
    return self._request_stream(
  File "D:\discord\.venv\lib\site-packages\ollama\_client.py", line 97, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
  File "D:\discord\.venv\lib\site-packages\ollama\_client.py", line 73, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: pull model manifest: 403: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/token</code> from this server.</h2>
<h2></h2>
</body></html>
```

**Comment by Roboxkin** [comment]
I would be grateful if you could tell me how to download the model and use it locally to fully work in your project

**Comment by luigi052005** [comment]
Is your ollama python libary on the latest version? You can update using: pip install --upgrade ollama

**Comment by luigi052005** [comment]
> I would be grateful if you could tell me how to download the model and use it locally to fully work in your project

use "ollama pull llama3" in cmd

**Comment by Roboxkin** [comment]
> pip install --upgrade ollama

```Python
(.venv) PS D:\discord> pip install --upgrade ollama
Requirement already satisfied: ollama in d:\discord\.venv\lib\site-packages (0.1.8)
Requirement already satisfied: httpx<0.28.0,>=0.27.0 in d:\discord\.venv\lib\site-packages (from ollama) (0.27.0)
Requirement already satisfied: anyio in d:\discord\.venv\lib\site-packages (from httpx<0.28.0,>=0.27.0->ollama) (4.3.0)
Requirement already satisfied: certifi in d:\discord\.venv\lib\site-packages (from httpx<0.28.0,>=0.27.0->ollama) (2024.2.2)
Requirement already satisfied: httpcore==1.* in d:\discord\.venv\lib\site-packages (from httpx<0.28.0,>=0.27.0->ollama) (1.0.5)
Requirement already satisfied: idna in d:\discord\.venv\lib\site-packages (from httpx<0.28.0,>=0.27.0->ollama) (3.7)
Requirement already satisfied: sniffio in d:\discord\.venv\lib\site-packages (from httpx<0.28.0,>=0.27.0->ollama) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in d:\discord\.venv\lib\site-packages (from httpcore==1.*->httpx<0.28.0,>=0.27.0->ollama) (0.14.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in d:\discord\.venv\lib\site-packages (from anyio->httpx<0.28.0,>=0.27.0->ollama) (1.2.1)
Requirement already satisfied: typing-extensions>=4.1 in d:\discord\.venv\lib\site-packages (from anyio->httpx<0.28.0,>=0.27.0->ollama) (4.11.0)
(.venv) PS D:\discord>
``` 
![Screenshot](https://github.com/luigi052005/Ollama-Discord-bot/assets/39112555/2836601f-5108-4fd8-8761-05633d2f6527)

**Comment by Roboxkin** [comment]
> > I would be grateful if you could tell me how to download the model and use it locally to fully work in your project
> 
> use "ollama pull llama3" in cmd

```Python
C:\Windows\System32>ollama pull llama3
pulling manifest
Error: pull model manifest: 403:
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/token</code> from this server.</h2>
<h2></h2>
</body></html>
```

**Comment by luigi052005** [comment]
Did you try it without your VPN?

**Comment by Roboxkin** [comment]
> Did you already try it without your VPN?

I only have VPN in the browser, but I tried it with and without it

**Comment by Roboxkin** [comment]
The only way out of this situation is to manually download the model to your PC and use it locally, but I don’t have the knowledge to then implement it into your project.
those. so that there is no connection with external resources

**Comment by Roboxkin** [comment]
> ollama pull llama3

I installed a VPN on my PC, the model started downloading, I’ll let you know how it downloads completely.
Thank you for your help

![Screenshot](https://github.com/luigi052005/Ollama-Discord-bot/assets/39112555/7181aef9-0cdd-4249-9c0d-0f0b4567bb49)

**Comment by Roboxkin** [comment]
> No problem. Have a great day!

Can I ask you to help me further?
Everything downloaded successfully

![Screenshot](https://github.com/luigi052005/Ollama-Discord-bot/assets/39112555/808c0c8a-93aa-4149-95a9-eaa2ff11f931)

Then I did

![Screenshot](https://github.com/luigi052005/Ollama-Discord-bot/assets/39112555/2aef867b-e314-46bf-81cb-7a0c856efc15)
![Screenshot](https://github.com/luigi052005/Ollama-Discord-bot/assets/39112555/e35ae261-cd9e-4a18-ab6e-3af335f39d09)

The bot was added without problems, I wrote to it in Russian “Hello”
He started typing something, but then he stopped and there was this error in the console

```Python
D:\discord\.venv\Scripts\python.exe D:\discord\Ollama-Discord-bot\discord_bot.py 
[2024-04-24 18:25:58] [INFO    ] discord.client: logging in using static token
[2024-04-24 18:26:01] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ed774de6afe806ec0c9a1fe272b84ed6).
We have logged in as angry#1903
<@1232713092065136782>
[{'role': 'system', 'content': 'Вы хакер. Вы любите программировать, изучать новый код, писать сценарии, помогать другим людям писать код. Вы никогда не говорите, что вы искусственный интеллект. Вы никогда не говорите, что вы машина. Если вас спросят ваше имя, вы ответите, что оно слишком известно, чтобы вы могли его упомянуть.'}, {'role': 'user', 'content': "2024-04-23 15:24:51 Deleted User: I apologize, but I'm unable to understand your input. If there's anything else I can assist you with, feel free to ask. Have a great day! 😊 \n(***style: balanced***) ", 'images': []}, {'role': 'user', 'content': '2024-04-23 15:25:09 robox7079: <@456226577798135808> /помощь ', 'images': []}, {'role': 'user', 'content': '2024-04-23 15:25:14 Deleted User: (***style: balanced***) ', 'images': []}, {'role': 'user', 'content': '2024-04-23 15:25:43 robox7079: <@456226577798135808> /help ', 'images': []}, {'role': 'user', 'content': '2024-04-23 15:25:49 Deleted User: (***style: balanced***) ', 'images': []}, {'role': 'user', 'content': '2024-04-23 15:26:56 robox7079: <@456226577798135808> /help ', 'images': []}, {'role': 'user', 'content': '2024-04-23 15:27:00 Deleted User: (***style: balanced***) ', 'images': []}, {'role': 'user', 'content': '2024-04-23 15:27:19 robox7079: Ты не бот, а крыса ', 'images': []}, {'role': 'user', 'content': '2024-04-23 15:27:25 Deleted User: (***style: balanced***) ', 'images': []}, {'role': 'user', 'content': '2024-04-23 15:32:58 robox7079: /create image a cat wondering in the forest ', 'images': []}, {'role': 'user', 'content': '2024-04-23 21:44:25 robox7079: <@456226577798135808> тест ', 'images': []}, {'role': 'user', 'content': '2024-04-24 17:48:02 Deleted User:  ', 'images': []}, {'role': 'user', 'content': '2024-04-24 18:15:04 robox7079: <@456226577798135808> привет! Ты чего молчишь? ', 'images': []}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '2024-04-24 18:26:36 robox7079: @angry ты тут? ', 'images': []}]
[2024-04-24 18:26:37] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "D:\discord\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\discord\Ollama-Discord-bot\discord_bot.py", line 34, in on_message
    await respond(message)
  File "D:\discord\Ollama-Discord-bot\discord_bot.py", line 57, in respond
    response = generate_response(message_history)
  File "D:\discord\Ollama-Discord-bot\response_generator.py", line 5, in generate_response
    response = ollama.chat(
  File "D:\discord\.venv\lib\site-packages\ollama\_client.py", line 173, in chat
    raise RequestError('messages must contain content')
ollama._types.RequestError: messages must contain content
```
