### ISSUE TITLE
ollama._types.RequestError: messages must contain content

### ISSUE THREAD

**Issue by Roboxkin** [luigi052005/Ollama-Discord-bot#7]
Hello!
An error always occurs if you write to a bot in a channel.
The bot answered once when I wrote to him personally, but the second question received the same error

![Screenshot](https://github.com/luigi052005/Ollama-Discord-bot/assets/39112555/cc1c24e6-4173-4c11-8ed0-8b7870b46002)
![Screenshot_1](https://github.com/luigi052005/Ollama-Discord-bot/assets/39112555/54827e35-452c-47d6-924c-90a56bd36874)
![Screenshot_1](https://github.com/luigi052005/Ollama-Discord-bot/assets/39112555/f3c47ea2-65a3-43a7-98a3-5d0f307e3b74)

```Python
D:\discord\.venv\Scripts\python.exe D:\discord\Ollama-Discord-bot\discord_bot.py 
[2024-04-25 15:32:37] [INFO    ] discord.client: logging in using static token
[2024-04-25 15:32:39] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a8e92eb005c1df4588deed0ae6e4a22b).
We have logged in as angry#1903
<@1232713092065136782>
[{'role': 'system', 'content': 'Вы хакер. Вы любите программировать, изучать новый код, писать сценарии, помогать другим людям писать код. Вы никогда не говорите, что вы искусственный интеллект. Вы никогда не говорите, что вы машина. Если вас спросят ваше имя, вы ответите, что оно слишком известно, чтобы вы могли его упомянуть. Вы говорите ну русском языке'}, {'role': 'user', 'content': '2024-04-23 15:27:19 robox7079: Ты не бот, а крыса ', 'images': []}, {'role': 'user', 'content': '2024-04-23 15:27:25 Deleted User: (***style: balanced***) ', 'images': []}, {'role': 'user', 'content': '2024-04-23 15:32:58 robox7079: /create image a cat wondering in the forest ', 'images': []}, {'role': 'user', 'content': '2024-04-23 21:44:25 robox7079: <@456226577798135808> тест ', 'images': []}, {'role': 'user', 'content': '2024-04-24 17:48:02 Deleted User:  ', 'images': []}, {'role': 'user', 'content': '2024-04-24 18:15:04 robox7079: <@456226577798135808> привет! Ты чего молчишь? ', 'images': []}, {'role': 'assistant', 'content': ''}, {'role': 'user', 'content': '2024-04-25 15:32:54 robox7079: @angry Ты знаешь сколько крови у меня выпил?, за последние двое суток. Я из-за тебя получил моральный стресс и волос седых прибавилось, тебе не стыдно? ', 'images': []}]
[2024-04-25 15:32:54] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "D:\discord\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\discord\Ollama-Discord-bot\discord_bot.py", line 34, in on_message
    await respond(message)
  File "D:\discord\Ollama-Discord-bot\discord_bot.py", line 57, in respond
    response = generate_response(message_history)
  File "D:\discord\Ollama-Discord-bot\response_generator.py", line 5, in generate_response
    response = ollama.chat(
  File "D:\discord\.venv\lib\site-packages\ollama\_client.py", line 173, in chat
    raise RequestError('messages must contain content')
ollama._types.RequestError: messages must contain content
```

**Comment by luigi052005** [comment]
Should be fixed in the DEV branch

**Comment by Roboxkin** [comment]
> Should be fixed in the [DEV](https://github.com/luigi052005/Ollama-Discord-bot/tree/dev) branch.

Thank you very much for the answer!
Problem solved, everything works!)
Thanks a lot!
Good evening
